include $(SDK_PATH)/build/env/common.mak

DST_NAME = libc.a

SRCS = \
atof.c atoi.c atol.c atoll.c \
jrand48.c lrand48.c mrand48.c nrand48.c seed48.c srand48.c \
bzero.c memccpy.c memswap.c \
memchr.c memrchr.c memmem.c memcmp.c \
bsearch.c qsort.c fnmatch.c \
snprintf.c sprintf.c sscanf.c \
vsnprintf.c vsprintf.c vsscanf.c \
strcmp.c strncmp.c strcasecmp.c strncasecmp.c \
strcpy.c strlcpy.c strncpy.c strcat.c strlcat.c strncat.c \
strlen.c strnlen.c \
strchr.c strrchr.c strsep.c strstr.c \
strcspn.c strspn.c strxspn.c strpbrk.c \
strtok.c strtok_r.c \
strtol.c strtoll.c strtoul.c strtoull.c \
strtoimax.c strtoumax.c strntoimax.c strntoumax.c \
ctype_isalnum.c ctype_isalpha.c ctype_isascii.c ctype_isblank.c \
ctype_iscntrl.c ctype_isdigit.c ctype_isgraph.c ctype_islower.c \
ctype_isprint.c ctype_ispunct.c ctype_isspace.c ctype_isupper.c \
ctype_isxdigit.c ctype_tolower.c ctype_toupper.c ctypes.c

all:  lib

include $(SDK_PATH)/build/env/rules.mak
