# Copyright (C) 2008-2012 Marvell International Ltd.
# All Rights Reserved.

include $(SDK_PATH)/build/env/common.mak

DST_NAME = libxz.a

SRCS = xz_crc32.c xz_dec_lzma2.c xz_dec_stream.c decompress.c

all:  lib

include $(SDK_PATH)/build/env/rules.mak
