# Copyright (C) 2008-2012 Marvell International Ltd.
# All Rights Reserved.


DST_NAME = pm_mc200_demo
SRCS = pm_mc200_demo.c \
	    board.c \
		peripheralsOn.c \
		peripheralsOff.c \

LDSCRIPT = $(TOOLCHAIN_DIR)/mc200.ld

include $(TOOLCHAIN_DIR)/targets.mk
include $(TOOLCHAIN_DIR)/rules.mk
